# .github/workflows/alert.yml
name: Daily Nouki Alerts

on:
  schedule:
    # 毎日 08:00 JST = 毎日 23:00 UTC
    - cron: '0 23 * * *'
  workflow_dispatch:    # 手動実行ボタン

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ▼ 4本あるスクリプトを順に実行 ▼
      - name: Run 裁断 7日前
        run: python alert_saidan.py
        env: ${{ secrets }}          # Secrets 全部注入

      - name: Run 補正 7日前
        run: python alert_housei.py
        env: ${{ secrets }}

      - name: Run 量産 7日前
        run: python alert_nouki.py
        env: ${{ secrets }}

      - name: Run 生産職出し 1日前
        run: python alert_syokudasi.py
        env: ${{ secrets }}
