# .github/workflows/alert.yml
name: Daily Nouki Alerts

# 毎朝 8:00 JST → UTC の 23:00 (前日)
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest

    # ── Secrets をまとめて環境変数に展開 ────────────────────────────
    env:
      DROPBOX_APP_KEY:       ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET:    ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
      SMTP_SERVER:           ${{ secrets.SMTP_SERVER }}
      SMTP_PORT:             ${{ secrets.SMTP_PORT }}
      SMTP_USER:             ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD:         ${{ secrets.SMTP_PASSWORD }}
      EMAIL_RECIPIENTS:      ${{ secrets.EMAIL_RECIPIENTS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      # ── デバッグ出力 ───────────────────────────────────────────
      - name: Debug: print SMTP settings
        run: |
          echo "SMTP_SERVER      = '${{ env.SMTP_SERVER }}'"
          echo "SMTP_PORT        = '${{ env.SMTP_PORT }}'"
          echo "SMTP_USER        = '${{ env.SMTP_USER }}'"
          echo "EMAIL_RECIPIENTS = '${{ env.EMAIL_RECIPIENTS }}'"

      # ── 4本のスクリプトを順に実行 ───────────────────────────────
      - name: Run 裁断 7日前 (alert_saidan.py)
        run: python alert_saidan.py

      - name: Run 補正 7日前 (alert_housei.py)
        run: python alert_housei.py

      - name: Run 量産 7日前 (alert_nouki.py)
        run: python alert_nouki.py

      - name: Run 生産職出し 1日前 (alert_syokudasi.py)
        run: python alert_syokudasi.py
